#------------------------------------------------------------------------------------
/gps/source/intensity 1
/gps/particle gamma
/gps/pos/type Point
/gps/pos/centre 0.0  0.0  -5.0 cm
/gps/ang/type iso
/gps/ene/type Mono
/gps/ene/mono 1 MeV

#------------------------------------------------------------------------------------
/gps/source/add 2 # add intensity x another source
/gps/particle gamma
/gps/pos/type Point
/gps/pos/centre 0.0  1.0  -4.0 cm
/gps/ang/type iso
/gps/ene/type Mono
/gps/ene/mono 1 MeV